### ISSUE TITLE
I get a Ready to create an app

### ISSUE THREAD

**Issue by bob5731** [makers-upv/smartpill-webui#1]
Can I get the STL files split up for this project? I'd love to be able to print this project and would it be possible to add up to 10 different pills to be spins that one time.
How do I setup the SmartPill Web App. Win I run the SmartPill Web App I get a Ready to create an app. So what do I need to do make it work and the ip is 192.168.50.60 of my SmartPill

**Comment by jaimelaborda** [comment]
Sorry @bob5731, the project is provided "as it is". We cannot provide support as we are working with other projects.

For the webui, it is developed using Ionic Angular framework. Just clone the repo and run "npm install" to install the required package. Then run "ionic serve" to run the development server or compile the app to run it on your own HTTP server.

You can get the STL files on Thingiverse or Hackster.io. Download the assembly and then use your slicer (Cura, PrusaSlicer, etc) to split the parts.

**Comment by bob5731** [comment]
Would you happen to have a pre-built image with everything installed?

**Comment by bob5731** [comment]
can back end be run on a raspberry pi?
